### ISSUE TITLE
Segfault in openzwave library

### ISSUE THREAD

**Issue by dhylands** [fxbox/openzwave-rust#30]
If I fire up openzwave-rust-example, btthen very shortly after receiving the AllNodesQueried notification then I get a segfault (I built the openzwave library with BUILD=DEBUG to get detailed info):

```
AllNodesQueried: Static Controller: HomeId: db421a3b Node: 1 Path: /dev/ttyACM0

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5bff700 (LWP 32740)]
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:140
140 ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:140
#1  0x0000555555675580 in OpenZWave::ValueRaw::OnValueRefreshed (this=0x7ffff4e14200, _value=0x0, _length=1 '\001')
    at /home/work/fxbox/openzwave-rust/openzwave-sys/open-zwave/cpp/src/value_classes/ValueRaw.cpp:280
#2  0x000055555566b3d5 in OpenZWave::UserCode::HandleMsg (this=0x7ffff4e7a000, _data=0x7ffff5bfe858 "\003\003", _length=4, _instance=1)
    at /home/work/fxbox/openzwave-rust/openzwave-sys/open-zwave/cpp/src/command_classes/UserCode.cpp:267
#3  0x0000555555612834 in OpenZWave::Node::ApplicationCommandHandler (this=0x7ffff4e3f300, _data=0x7ffff5bfe852 "", encrypted=true)
    at /home/work/fxbox/openzwave-rust/openzwave-sys/open-zwave/cpp/src/Node.cpp:1858
#4  0x00005555556876ca in OpenZWave::Driver::HandleApplicationCommandHandlerRequest (this=0x7ffff5c5b000, _data=0x7ffff5bfe852 "", encrypted=true)
    at /home/work/fxbox/openzwave-rust/openzwave-sys/open-zwave/cpp/src/Driver.cpp:3536
#5  0x0000555555683583 in OpenZWave::Driver::ProcessMsg (this=0x7ffff5c5b000, _data=0x7ffff5bfe852 "") at /home/work/fxbox/openzwave-rust/openzwave-sys/open-zwave/cpp/src/Driver.cpp:2138
#6  0x0000555555682195 in OpenZWave::Driver::ReadMsg (this=0x7ffff5c5b000) at /home/work/fxbox/openzwave-rust/openzwave-sys/open-zwave/cpp/src/Driver.cpp:1719
#7  0x000055555567e1dd in OpenZWave::Driver::DriverThreadProc (this=0x7ffff5c5b000, _exitEvent=0x7ffff5c1d340) at /home/work/fxbox/openzwave-rust/openzwave-sys/open-zwave/cpp/src/Driver.cpp:480
#8  0x000055555567de1e in OpenZWave::Driver::DriverThreadEntryPoint (_exitEvent=0x7ffff5c1d340, _context=0x7ffff5c5b000)
    at /home/work/fxbox/openzwave-rust/openzwave-sys/open-zwave/cpp/src/Driver.cpp:383
#9  0x00005555556b051e in OpenZWave::ThreadImpl::Run (this=0x7ffff5c279c0) at /home/work/fxbox/openzwave-rust/openzwave-sys/open-zwave/cpp/src/platform/unix/ThreadImpl.cpp:176
#10 0x00005555556b04e2 in OpenZWave::ThreadImpl::ThreadProc (_pArg=0x7ffff5c279c0) at /home/work/fxbox/openzwave-rust/openzwave-sys/open-zwave/cpp/src/platform/unix/ThreadImpl.cpp:161
#11 0x00007ffff74ab182 in start_thread (arg=0x7ffff5bff700) at pthread_create.c:312
#12 0x00007ffff6fc247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by dhylands** [comment]
It turns out that this doesn't happen on the branch that we're using, but it does happen on the latest branch in the open-zwave repository.

The problem was introduced with this commit:
https://github.com/OpenZWave/open-zwave/commit/0d716a3526eea2c23691c90073c3c5895af3bd24#diff-ff7e1d741538bd919041a0ae222fae88R267
(passing a null pointer to OnValueRefreshed).

**Comment by julienw** [comment]
Do you know if that's been fixed upstream ? Have you filed a bug there ?

**Comment by julienw** [comment]
OK, looks like it's been fixed in https://github.com/OpenZWave/open-zwave/commit/4314523d320f96fd67a8692c3310bd7fedd7bc94

**Comment by julienw** [comment]
Reported in https://github.com/OpenZWave/open-zwave/issues/847.

**Comment by dhylands** [comment]
Yeah - I saw that crash report so didn't file a new one, and helped the guy get his PR in order. The fix landed a day or two ago.
